# Generated by Django 5.1.7 on 2025-06-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armoury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
